Set up tests for requiredCerts
gh-2

This includes a pretty infuriating issue relating to "const enum" vs
"enum." I got an error:

TypeError: Cannot read properties of undefined (reading 'FOUND')

before I changed `export enum` to `export const enum`, which is
seriously confusing.

https://stackoverflow.com/questions/50365598/typescript-runtime-error-cannot-read-property-of-undefined-enum